### ISSUE TITLE
Make self mutable in get_rows()

### ISSUE THREAD

**Issue by ycuk** [Synphonyte/leptos-struct-table#11]
Please replace
```rust
async fn get_rows(&self, range: Range<usize>) -> Vec<Row>;
```
to
```rust
async fn get_rows(&mut self, range: Range<usize>) -> Vec<Row>;
```
in 
```rust
pub trait TableDataProvider<Row>
```

When I send data from API, it also has `total` field to make calculations for paginator.
So it would be look like this
```rust
async fn get_rows(&mut self, range: Range<usize>) -> Vec<Profile> {
    let resp: Resp<Vec<Profile>> = get(self.get_url(range)).await;
    match resp {
        Resp::List {total, objs} => {
            self.total = total; // Total rows in DB table without 'LIMIT $1 OFFSET $2'
            objs
        },
        _ => vec![],
    }
}
```

**Comment by maccesch** [comment]
That makes sense! Give me a few minutes...

**Comment by maccesch** [comment]
This is actually not as easy as I initially thought. Right now this whole thing get's put into a `Resource` where we operate on a clone. I'll have to do some thinking about this.

**Comment by maccesch** [comment]
Ok I'm finally finishing a big refactoring which implements virtualization. Part of that now means that `get_rows` is called concurrently which makes it impossible to make `self` a mutable reference.

But there's now also `row_count` method which is meant to load the number of rows.

You could try using a stored value to make your calculations but I'm not sure if that leads to problems.

It might not be needed anymore though because we now also have pagination natively supported.
